### ISSUE TITLE
Handle base path

### ISSUE THREAD

**Issue by darccio** [imdario/gluo#4]
Check if it's possible to infer base path from APIGatewayProxyRequest's following fields:

- resource
- requestContext.resourcePath
- path

If not, get it from an environment variable and document it.

Implement using these as guide:

- https://github.com/apex/gateway/pull/4
- https://github.com/awslabs/aws-serverless-express/issues/86
- https://github.com/awslabs/aws-serverless-java-container/blob/f634f6e3f30e859687eb33814df1085a2a6e3f63/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/RequestReader.java#L89

**Comment by bsdkurt** [comment]
Isn't this as easy as the following change? index.js line 21:
```
-  return url.format({ pathname: event.path, query: event.queryStringParameters })
+ return url.format({ pathname: event.resource, query: event.queryStringParameters })
